### ISSUE TITLE
Dead and wrong implementation of session service API

### ISSUE THREAD

**Issue by robbl-as** [controlshift/campact-user-service#8]
While working on the preparation for the WeAct migration and to make sure we know all endpoints and data Agra uses from campact sessions and user service, we had a look at your code. We've noticed this [method](https://github.com/controlshift/campact-user-service/blob/ba46b835e77634a68c3ac818f0a3dbe1a69c838a/lib/campact_user_service/session.rb#L11) is not used by tokyo and probably could be removed. Also, there is no `id` in the session payload, it should be `session_id`. We were quite confused when we first looked at this piece of code and thought soft login was broken. :)

**Comment by anero** [comment]
Hmm all of this classes' methods are using the [`session` method](https://github.com/controlshift/campact-user-service/blob/ba46b835e77634a68c3ac818f0a3dbe1a69c838a/lib/campact_user_service/session.rb#L33) that retrieves the session via the API using the `session_id` attribute value as a cookie. 
I haven't tested now, but from looking at the code and from the specs (https://github.com/controlshift/campact-user-service/blob/ba46b835e77634a68c3ac818f0a3dbe1a69c838a/spec/session_spec.rb#L10) it seems like this should work correctly.

**Comment by robbl-as** [comment]
1. The body of GET /v1/sessions does not return a `id`, it is `session_id`. See:

https://github.com/controlshift/campact-user-service/blob/ba46b835e77634a68c3ac818f0a3dbe1a69c838a/spec/session_spec.rb#L14

2. The method is not used and could be removed if not fixed.

**Comment by anero** [comment]
Thanks @rob-as I understand now. I removed the unused method and released a new version of the gem, will update tokyo shortly.
I noticed we also define an `exists?` method for `Account`: https://github.com/controlshift/campact-user-service/blob/a7f48ff5d6c0c6984c9cb5479caba73d1ce56a13/lib/campact_user_service/account.rb#L10. Could you confirm if in that case the API returns an `id` value or if we should be checking for `account_id`?

**Comment by robbl-as** [comment]
1. The body of GET /api/v1/accounts returns a `id`. This and your code is correct.
2. I'll take a note and maybe we unify this in the future.
